// Mocks generated by Mockito 5.1.0 from annotations
// in lite/redux/middleware.dart.
// Do not manually edit this file.

import 'package:lite/models/model.dart' as _i4;
import 'package:lite/redux/middleware.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:redux/redux.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DeviceApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceApi extends _i1.Mock implements _i2.DeviceApi {
  MockDeviceApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void getDevices(_i3.Store<_i4.AppState>? store) =>
      super.noSuchMethod(Invocation.method(#getDevices, [store]),
          returnValueForMissingStub: null);
}
